name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Daily security audit
    - cron: "0 3 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache Cargo registry and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 1. Tests
      - name: Run tests
        run: cargo test --all --all-features --locked --verbose

      # 2. Code coverage
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run coverage
        run: cargo tarpaulin --ignore-tests --out Xml

      # 3. Linting
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # 4. Formatting
      - name: Check formatting
        run: cargo fmt --all -- --check

      # 5. Security audit
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run security audit
        run: cargo audit --deny warnings

